### ISSUE TITLE
requirements.txt file

### ISSUE THREAD

**Issue by orchidas** [francesclluis/sound-field-neural-network#1]
I tried running
`conda env create -f environment.yml`

But I get the following errors
`Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - xorg-xproto==7.0.31=h14c3975_1007
  - xorg-renderproto==0.11.1=h14c3975_1002
  - expat==2.2.5=he1b5a44_1003
  - fontconfig==2.13.1=h86ecdb6_1001
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - qt==5.9.7=h0c104cb_3
  - libuuid==2.32.1=h14c3975_1000
  - sqlite==3.29.0=h7b6447c_0
  - zlib==1.2.11=h7b6447c_3
  - xorg-xextproto==7.3.0=h14c3975_1002
  - xorg-libxext==1.3.4=h516909a_0
  - lame==3.100=h14c3975_1001
  - dbus==1.13.6=he372182_0
  - matplotlib-base==3.1.1=py36he7580a8_1
  - harfbuzz==2.4.0=h9f30f68_2
  - grpcio==1.16.1=py36hf8bcb03_1
  - jpeg==9c=h14c3975_1001
  - openssl==1.1.1=h7b6447c_0
  - mkl_random==1.0.4=py36hf2d7682_0
  - readline==7.0=h7b6447c_5
  - libxcb==1.13=h14c3975_1002
  - icu==64.2=he1b5a44_0
  - libtiff==4.0.10=h2733197_2
  - mkl==2019.4=243
  - xz==5.2.4=h14c3975_4
  - protobuf==3.8.0=py36he6710b0_0
  - numpy-base==1.16.4=py36h2f8d375_0
  - pillow==6.1.0=py36h34e0f95_0
  - intel-openmp==2019.4=243
  - xorg-libice==1.0.10=h516909a_0
  - hdf5==1.10.5=nompi_h3c11f04_1100
  - pywavelets==1.0.3=py36hdd07704_1
  - ncurses==6.1=he6710b0_1
  - nettle==3.4.1=h1bed415_1002
  - mkl_fft==1.0.14=py36h516909a_1
  - x264==1!152.20180806=h14c3975_0
  - xorg-kbproto==1.0.7=h14c3975_1002
  - xorg-libxrender==0.9.10=h516909a_1002
  - cudatoolkit==8.0=3
  - xorg-libxdmcp==1.1.3=h516909a_0
  - h5py==2.9.0=nompi_py36h513d04c_1104
  - libgcc-ng==9.1.0=hdf63c60_0
  - cudnn==7.1.3=cuda8.0_0
  - tornado==6.0.3=py36h516909a_0
  - jasper==1.900.1=h07fcdf6_1006
  - opencv==4.1.1=py36ha799480_1
  - zstd==1.3.7=h0b5b093_0
  - xorg-libx11==1.6.8=h516909a_0
  - ffmpeg==4.1.3=h167e202_0
  - pcre==8.41=hf484d3e_1003
  - libxml2==2.9.9=hee79883_2
  - libgfortran-ng==7.3.0=hdf63c60_0
  - libffi==3.2.1=hd88cf55_4
  - libiconv==1.15=h516909a_1005
  - giflib==5.1.9=h516909a_0
  - pandas==0.25.0=py36he6710b0_0
  - tk==8.6.9=hed695b0_1002
  - cytoolz==0.10.0=py36h7b6447c_0
  - wrapt==1.11.2=py36h7b6447c_0
  - c-ares==1.15.0=h7b6447c_1001
  - pyqt==5.9.2=py36hcca6a23_2
  - scipy==1.3.1=py36h921218d_0
  - gst-plugins-base==1.14.5=h0935bb2_0
  - scikit-image==0.15.0=py36he6710b0_0
  - cupti==8.0.61=0
  - libprotobuf==3.8.0=hd408876_0
  - kiwisolver==1.1.0=py36hc9558a2_0
  - tensorboard==1.10.0=py36hf484d3e_0
  - libpng==1.6.37=hed695b0_0
  - tensorflow-base==1.10.0=gpu_py36h3435052_0
  - gstreamer==1.14.5=h36ae1b5_0
  - xorg-libxau==1.0.9=h14c3975_0
  - xorg-libsm==1.2.3=h84519dc_1000
  - numpy==1.16.4=py36h99e49ec_0
  - glib==2.58.3=h6f030ca_1002
  - libwebp==1.0.2=h576950b_1
  - gmp==6.1.2=hf484d3e_1000
  - libopenblas==0.3.6=h6e990d7_6
  - gettext==0.19.8.1=hc5be6a0_1002
  - libedit==3.1.20181209=hc058e9b_0
  - tensorflow==1.10.0=gpu_py36h8dbd23f_0
  - openh264==1.8.0=hdbcaa40_1000
  - graphite2==1.3.13=hf484d3e_1000
  - yaml==0.1.7=h96e3832_1
  - mkl-service==2.0.2=py36h7b6447c_0
  - python==3.6.8=h0371630_0
  - pthread-stubs==0.4=h14c3975_1001
  - sip==4.19.8=py36hf484d3e_1000
  - cairo==1.16.0=hfb77d84_1002
  - freetype==2.10.0=he983fc9_0
  - pyyaml==5.1.1=py36h7b6447c_0
  - pixman==0.38.0=h516909a_1003
  - bzip2==1.0.8=h516909a_0
  - gnutls==3.6.5=hd3a4fd2_1002`

 Will it be possible to provide a requirements.txt file for easy download of missing packages?

**Comment by francesclluis** [comment]
Hi!
I've also had a similar problem running it today..I've used the following to solve it:

`conda create -n test python=3.6`
`conda activate test`

`conda install -c anaconda scipy`
`conda install -c anaconda pandas`
`conda install -c conda-forge matplotlib`
`conda install -c anaconda scikit-image`
`conda install -c conda-forge keras==2.2.4`
`conda install -c conda-forge opencv`

`git clone https://github.com/francesclluis/sound-field-neural-network.git`
`cd sound-field-neural-network/`
`./download_sample_dataset.sh`

`python main.py --mode train --config config/config.json`

Hope it works for you too!

**Comment by orchidas** [comment]
Thank you! I also solved the problem yesterday by downloading these packages, and also downgraded my conda version to 4.6.14. Downgrading Python from 3.8 to 3.6 and conda to 4.6.14 and manually installing these packages made everything run smoothly.

**Comment by xiaozhi2015** [comment]
@francesclluis  Do you still have sample_datasets.tgz? The download link is no longer valid in download_sample_dataset.sh.

**Comment by francesclluis** [comment]
Hi @xiaozhi2015! You can download the sample_datasets folder from the following google drive link: https://drive.google.com/file/d/1dgmN9pVSv2WPAYqDS7SX1CUcidgd7N9h/view?usp=sharing

**Comment by xiaozhi2015** [comment]
thx! @francesclluis
